service: bref-demo

provider:
    name: aws
    region: us-west-2
    memorySize: 128
    timeout: 29

plugins:
    - ./vendor/bref/bref

functions:
    index:
        handler: index.php
        runtime: php-83-fpm
        events:
            - httpApi:
                path: /
                method: get
    hello:
        handler: hello.php
        runtime: php-83-fpm
        events:
            - httpApi:
                path: /hello
                method: any

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
