service: bref-demo

provider:
    name: aws
    region: us-west-2
    runtime: provided.al2
    memorySize: 128

plugins:
    - ./vendor/bref/bref

functions:
    index:
        handler: index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - http:
                path: '/'
                method: 'get'
    hello:
        handler: hello.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - http:
                path: 'hello'
                method: 'ANY'

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
